name: ci3
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Android NDK
        uses: uraimo/run-on-arch-action@v2.6.0
        with:
         arch: aarch64
         distro: ubuntu22.04
         shell: /usr/bin/bash
         run: |
          sudo apt install -y curl
          mkdir home
          cd home
          export HOME=$(pwd)
          mkdir -p ~/bin
          curl -L https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH="$HOME/bin:$PATH"
          mkdir ndk
          cd ndk
          repo init -u https://android.googlesource.com/platform/manifest -b master-ndk --depth=1
          repo sync -cj 12
          cd ndk
          sudo apt install -y pipx
          pipx install poetry
          poetry env use ../prebuilts/python/linux-x86/bin/python3
          poetry install
          poetry run ./checkbuild.py --no-build-tests || true

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
