name: docker test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: zfs
        run: |
           sudo apt install zfsutils-linux
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
