name: lxc
on:
  workflow_dispatch:
env:
  CONTAINER_NAME: "ubuntu"
  IMAGE_NAME: "jammy"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kernel Modules
        run: |
          sudo apt install -y linux-modules-extra-$(uname -r)
          sudo mkdir -p /dev/binderfs
          sudo modprobe binder_linux
          sudo mount -t binder binder /dev/binderfs

          for i in binder hwbinder vndbinder; do
            sudo ln -nsf "/dev/binderfs/${i}" "/dev/${i}"
          done

          git clone --depth 1 https://github.com/choff/anbox-modules
          cd anbox-modules/ashmem
          make -j $(nproc --all)
          sudo insmod ashmem_linux.ko
          
          # for i in $(sudo find /lib/modules/*-azure -type f -name "*\.ko"); do
          #   sudo modprobe "$(basename "${i}" | sed -E 's/\.ko$//')"
          # done
          
      - name: Setup Waydroid
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install -y curl ca-certificates
          curl https://repo.waydro.id | sudo bash
          sudo apt install -y waydroid weston

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
