name: ci3
on:
  workflow_dispatch:
env:
  CONTAINER_NAME: "ubuntu"
  IMAGE_NAME: "jammy"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remove unnecessary packages
        run: |
          # sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(cabal-|dotnet-|ghc-|libmono|php|aspnetcore)') mono-runtime-common monodoc-manual ruby &>/dev/null
          # sudo apt autoremove -yq &>/dev/null
          # sudo rm -rf /opt/hostedtoolcache /usr/local /usr/share/dotnet /usr/share/swift
          
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'
          remove-codeql: 'false'
          remove-docker-images: 'false'

      - name: Setup LXC
        run: |
          sudo apt install -y lxc
          sudo lxc-create -t download -n "${{ env.CONTAINER_NAME }}" -- -d ubuntu -r "${{ env.IMAGE_NAME }}" -a amd64

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
