name: lxc
on:
  workflow_dispatch:
env:
  CONTAINER_NAME: "ubuntu"
  IMAGE_NAME: "jammy"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup LXC
        run: |
          sudo apt install -y lxc
          sudo lxc-create -t download -n "${{ env.CONTAINER_NAME }}" -- -d ubuntu -r "${{ env.IMAGE_NAME }}" -a amd64

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
