name: waydroid
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kernel Modules
        run: |
          sudo apt install -y linux-modules-extra-$(uname -r)
          sudo mkdir -p /dev/binderfs
          sudo modprobe binder_linux
          sudo mount -t binder binder /dev/binderfs

          for i in binder hwbinder vndbinder; do
            sudo ln -nsf "/dev/binderfs/${i}" "/dev/${i}"
          done

          git clone --depth 1 https://github.com/choff/anbox-modules
          cd anbox-modules/ashmem
          make -j $(nproc --all)
          sudo insmod ashmem_linux.ko
          
          # for i in $(sudo find /lib/modules/*-azure -type f -name "*\.ko"); do
          #   sudo modprobe "$(basename "${i}" | sed -E 's/\.ko$//')"
          # done
          
      - name: Setup Waydroid
        run: |
          sudo apt update -y
          # sudo apt install -y tigervnc-standalone-server openbox libdbus-glib-1-dev libgbm-dev weston
          sudo apt install -y adb weston
          sudo apt install -y curl ca-certificates
          curl https://repo.waydro.id | sudo bash
          sudo apt install -y waydroid
          sudo waydroid init -s GAPPS &>/dev/null
          ( weston --socket waydroid  --backend headless-backend.so --width 486 --height 1000 &>/dev/null & )
          sleep 1
          ( WAYLAND_DISPLAY=waydroid waydroid session start &>/dev/null & )
          exit 0
          wget https://downloads.realvnc.com/download/file/vnc.files/VNC-Server-7.9.0-Linux-x64.deb -O VNC-Server-Linux-x64.deb
          sudo setfacl -m u:_apt:rwx VNC-Server-Linux-x64.deb
          sudo apt install ./VNC-Server-Linux-x64.deb
          exit 0
          # sudo apt upgrade -y
          sudo apt install -y curl ca-certificates
          curl https://repo.waydro.id | sudo bash
          sudo apt install lxc
          exit 0
          # sudo apt install -yq waydroid tigervnc-standalone-server weston xfce4 xfce4-terminal
          # sudo waydroid init -s GAPPS &>/dev/null
          export DISPLAY="${{ env.DISPLAY }}"
          mkdir -p "$HOME/.vnc"
          chmod go-rwx "$HOME/.vnc"
          echo -e "password\npassword\n" | vncpasswd
          vncserver -localhost no "${{ env.DISPLAY }}"
          ( weston --socket "${{ env.WAYLAND_DISPLAY }}" --backend x11-backend.so &>/dev/null & )
          sudo waydroid init -s GAPPS &>/dev/null
          ( WAYLAND_DISPLAY="${{ env.WAYLAND_DISPLAY }}" waydroid session start &>/dev/null & )

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
